### ISSUE TITLE
A Problem with the mod 

### ISSUE THREAD

**Issue by llrluis** [PotatoPresident/PetOwner#12]
Hello, I have a problem with the mod. When I approach a pet it shows me the message "Something went wrong" but in the chat it shows me the owner of the pet correctly.

Additionally when I right click on a cat it shows me the owner duplicated.

The owner's visualization problem happens to me with all pets.

I attach images of the problem

![Dog](https://user-images.githubusercontent.com/72475671/95268991-1af0ac00-07fe-11eb-997e-7525e1f988d6.png)
![Cat](https://user-images.githubusercontent.com/72475671/95268997-1cba6f80-07fe-11eb-8c51-b1655444521b.png)
![Horse](https://user-images.githubusercontent.com/72475671/95268999-1deb9c80-07fe-11eb-9462-91b439f92f0d.png)

Thank you very much for your support :)

**Comment by PotatoPresident** [comment]
Sorry for the delay, have been very busy.  So I have a few questions. 

First of all, I don't even recognize the message that is in chat, I don't believe it's in any of the [translation files](https://github.com/PotatoPresident/PetOwner/tree/master/src/main/resources/assets/petowner/lang). Next question, is this a cracked/non premium server? I ask because the name _AlpacunaHot_ does not show up in the mojang API. If not, does the server have multiple worlds?

**Comment by llrluis** [comment]
Hello, to answer the questions:

1. I have realized that the chat message is a plugin of the server where I am playing.
2. The server is not premium, I can provide you with the ip if you want to try the mod on the server.

Thank you very much for your support!

**Comment by PotatoPresident** [comment]
Unfortunately the mod only works on premium servers because it has to get the username from the mojang API. I'll add that to the curseforge page, sorry!
